- name: Debian | Add Microsft apt keys
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Debian | Add VS Code apt repository
  apt_repository: 
    repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main' 
    state: present 
    filename: vscode

- name: Debian | Install VS Code
  apt:
    name: code
  state: present